---
title: "Getting Bricks Plot to Work!"
author: "Maia Smith"
date: "March 5, 2015"
output:
  html_document:
    keep_md: yes
---

```{r, echo=FALSE}
# install.packages("ggplot2")
# install.packages("grid")
# install.packages("plyr")
# install.packages("knitr")
# install.packages("devtools")
# install.packages("car")
# install.packages("plotly")
# install.packages("reshape2")
# install.packages("gplots")
# install.packages("RColorBrewer")
library(ggplot2)
library(grid)
library(gridExtra)
library(plyr)
library(knitr)
library(devtools)
library(car)
library(plotly)
library(reshape2)
library(gplots)
library(RColorBrewer)
py <- plotly("mas29", "8s6jru0os3")
dir = "/Users/maiasmith/Documents/SFU/ClarkeLab/ClarkeLab_github/"
#dir = "C:/Users/Dave/Documents/SFU job/Lab - muscle signaling/Dixon - myocyte expts/Maia Smith files/ClarkeLab_github/"
#dir = "/Users/mas29/Documents/ClarkeLab_github/"
load(file=paste(dir,"DataObjects/sytoxG_data.R",sep=""))
load(file=paste(dir,"DataObjects/confluency_data.R",sep=""))
load(file=paste(dir,"DataObjects/sytoxG_data_features.R",sep=""))
load(file=paste(dir,"DataObjects/confluency_data_features.R",sep=""))
load(file=paste(dir,"DataObjects/confluency_sytoxG_data.R",sep=""))
sm_ds <- sytoxG_data[1:2408,]

# Number of time intervals
num_time_intervals <- length(unique(sytoxG_data$time_elapsed))

# Confidence interval bounds
confidence_intervals_SG <- sytoxG_data[1:num_time_intervals,c("time_elapsed", "phenotype_value.NC.upper", "phenotype_value.NC.mean", "phenotype_value.NC.lower")]
confidence_intervals_Con <- confluency_data[1:num_time_intervals,c("time_elapsed", "phenotype_value.NC.upper", "phenotype_value.NC.mean", "phenotype_value.NC.lower")]

# Get rid of negative control data
sytoxG_data_no_NC <- sytoxG_data[which(sytoxG_data$empty == "Treatment"),]
confluency_data_no_NC <- confluency_data[which(confluency_data$empty == "Treatment"),]
```


```{r, echo=FALSE, fig.width=26, fig.height=26} 
sm_ds <- sytoxG_data_no_NC[1:3400,]
ggplot(sm_ds, 
       aes(x=as.numeric(time_elapsed), y=as.numeric(phenotype_value), 
           group=Compound)) +
  geom_rect(data = sm_ds, aes(xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf, fill = delta_min_max), alpha = 0.4) +
  geom_line() +
  scale_fill_gradient2(low = "red", mid = "white", high = "red",
                       midpoint = 0, space = "rgb", na.value = "grey50", guide = "colourbar") + 
  xlab("Time Elapsed") +
  ylab("Sytox Green") +
  ggtitle("Sytox Green - Muscle Cells Over Time") +
  facet_wrap(~ Compound, ncol = 43, scales = "fixed") +
  labs(fill = "Delta\n(max-min)") +
  theme(panel.grid = element_blank(),
        strip.text=element_blank(),
        axis.text = element_blank(),
        axis.ticks.length = unit(0, "cm"),
        legend.key.height = unit(.85, "cm"),
        panel.background = element_rect(fill = "white"),
        panel.margin = unit(.085, "cm"),
        axis.title.x = element_text(size = 20.5, angle = 00),
        axis.title.y = element_text(size = 20.5, angle = 90),
       title = element_text(size = 35, angle = 00),
        legend.text = element_text(size = 20.5, angle = 00))
```

```{r setup, include=FALSE}
opts_chunk$set(out.width='1000px', dpi=200)
```

Quality Control
=============

Compare controls and treatments
-----------------------------------------------
```{r, eval=FALSE, echo=FALSE}
plot <- ggplot(sytoxG_data, aes(x=as.numeric(time_elapsed), y=as.numeric(phenotype_value), text=Compound, group=Compound)) +
  geom_line() +
  xlab("Time Elapsed") +
  ylab("Sytox Green") +
  ggtitle("Sytox Green Over Time - Control vs Treatment") +
  facet_grid(~empty, scales = "fixed") +
  theme(panel.grid = element_blank(),
        axis.ticks.length = unit(0, "cm"),
        panel.background = element_rect(fill = "white"), 
        axis.text = element_blank())
response <- py$ggplotly(plot, kwargs=list(world_readable=FALSE, filename="SG_control_vs_treatment", fileopt="overwrite"))
url <- response$response$url
```
