---
title: "Pathway Analysis"
author: "Maia Smith"
date: "March 24, 2015"
output: html_document
---

Pathway analysis 
================

Note: To get the hover information working correctly on Plotly graphs (the interactive graphs), do the following: 
1. Hover anywhere over graph
2. You'll see icons appear at the top right-hand corner of the graph
3. Select the icon for "Show closest data on hover"

Sparklines by Pathway
------------------------

Compared to negative controls:

```{r, echo=FALSE, fig.width=15, fig.height=15}

# SG
ggplot(sytoxG_data) +
  geom_line(aes(x=as.numeric(time_elapsed), y=as.numeric(phenotype_value), group=Compound, text=Compound)) +
  geom_ribbon(data = confidence_intervals_SG, mapping = aes(x = time_elapsed, ymin = phenotype_value.NC.lower, ymax = phenotype_value.NC.upper,
                                                            fill = "red", colour = NULL), alpha = 0.6) +
  scale_fill_manual(name = "Legend",
                    values = c('red'),
                    labels = c('Negative Control\n99.9% C.I.')) +
  xlab("Time Elapsed") +
  ylab("Sytox Green") +
  ggtitle("Sytox Green - Facets: Pathway") +
  facet_wrap(~Pathway, ncol=6, scales = "fixed") +
  theme(panel.grid = element_blank(),
        axis.ticks.length = unit(0, "cm"),
        panel.background = element_rect(fill = "white"),
        axis.text = element_blank(),
        legend.direction="vertical")

# Confluency
ggplot(confluency_data) +
  geom_line(aes(x=as.numeric(time_elapsed), y=as.numeric(phenotype_value), group=Compound, text=Compound)) +
  geom_ribbon(data = confidence_intervals_Con, mapping = aes(x = time_elapsed, ymin = phenotype_value.NC.lower, ymax = phenotype_value.NC.upper,
                                                             fill = "red", colour = NULL), alpha = 0.6) +
  scale_fill_manual(name = "Legend",
                    values = c('red'),
                    labels = c('Negative Control\n99.9% C.I.')) +
  xlab("Time Elapsed") +
  ylab("Confluency") +
  ggtitle("Confluency - Facets: Pathway") +
  facet_wrap(~Pathway, ncol=6, scales = "fixed") +
  theme(panel.grid = element_blank(),
        axis.ticks.length = unit(0, "cm"),
        panel.background = element_rect(fill = "white"),
        axis.text = element_blank(),
        legend.direction="vertical")
```

Sparklines By Pathway, in Plotly:
-------

```{r, echo=FALSE, plotly=TRUE} 
SG_sparklines_by_pathway <- ggplot(sytoxG_data, 
               aes(x=as.numeric(time_elapsed), y=as.numeric(phenotype_value), group=Compound,
                   text=Compound)) +
  geom_line() +
  xlab("Time Elapsed") +
  ylab("Sytox Green") +
  ggtitle("Sytox Green - Facets: Pathway") +
  facet_wrap(~Pathway, ncol=6, scales = "fixed") +
  theme(panel.grid = element_blank(),
        axis.ticks.length = unit(0, "cm"),
        panel.background = element_rect(fill = "white"),
        strip.text.x = element_text(size=4),
        axis.text = element_blank())
py$ggplotly(SG_sparklines_by_pathway, session="knitr", kwargs=list(world_readable=FALSE, filename="SG_sparklines_by_pathway", fileopt="overwrite"))
```

```{r, echo=FALSE, plotly=TRUE} 
Con_sparklines_by_pathway <- ggplot(confluency_data, 
               aes(x=as.numeric(time_elapsed), y=as.numeric(phenotype_value), group=Compound,
                   text=Compound)) +
  geom_line() +
  xlab("Time Elapsed") +
  ylab("Confluency") +
  ggtitle("Confluency - Facets: Pathway") +
  facet_wrap(~Pathway, ncol=6, scales = "fixed") +
  theme(panel.grid = element_blank(),
        axis.ticks.length = unit(0, "cm"),
        panel.background = element_rect(fill = "white"),
        strip.text.x = element_text(size=4),
        axis.text = element_blank())
py$ggplotly(Con_sparklines_by_pathway, session="knitr", kwargs=list(world_readable=FALSE, filename="Con_sparklines_by_pathway", fileopt="overwrite"))
```

Delta (max-min) values by Pathway
----------------------------------

```{r, echo=FALSE, plotly=TRUE}
SG_delta_by_pathway <- ggplot(sytoxG_data_features, aes(Pathway, delta_min_max, text=Compound)) + 
  geom_point(alpha=0.4) +
  ylab("Delta (max-min)") +
  ggtitle("Sytox Green Delta (max-min) by Pathway") +
  theme(panel.grid = element_blank(),
        panel.background = element_rect(fill = "white"),
        axis.text.x = element_text(size=6, angle=75))
py$ggplotly(SG_delta_by_pathway, kwargs=list(world_readable=FALSE, filename="SG_delta_by_pathway", fileopt="overwrite"), session="knitr")
```

```{r, echo=FALSE, plotly=TRUE}
Con_delta_by_pathway <- ggplot(confluency_data_features, aes(Pathway, delta_min_max, text=Compound)) + 
  geom_point(alpha=0.4) +
  ylab("Delta (max-min)") +
  ggtitle("Confluency Delta (max-min) by Pathway") +
  theme(panel.grid = element_blank(),
        panel.background = element_rect(fill = "white"),
        axis.text.x = element_text(size=6, angle=75))
py$ggplotly(Con_delta_by_pathway, kwargs=list(world_readable=FALSE, filename="Con_delta_by_pathway", fileopt="overwrite"), session="knitr")
```

Which pathways are significantly different from the negative controls (measured by AUC)? 
------------------

For Sytox Green:

```{r, echo=FALSE}
# --> SG
fit_SG <- lm(AUC_trapezoidal_integration ~ Pathway, data_for_stats, subset = phenotypic_Marker == "SG")
summary <-  as.data.frame(summary(fit_SG)$coef)
sig_level <- 0.01
sig_pathways_SG <- rownames(summary[summary[,"Pr(>|t|)"] < sig_level,])
sig_pathways_SG <- gsub("Pathway","",sig_pathways_SG)
print(paste("The following pathways have an AUC for Sytox Green significantly different (p < ",sig_level,") from the negative controls' AUC?",sep=""))
print(sig_pathways_SG[2:length(sig_pathways_SG)])
```

For Confluency:

```{r, echo=FALSE} 
# --> Con
fit_Con <- lm(AUC_trapezoidal_integration ~ Pathway, data_for_stats, subset = phenotypic_Marker == "Con")
summary <-  as.data.frame(summary(fit_Con)$coef)
sig_level <- 0.01
sig_pathways_Con <- rownames(summary[summary[,"Pr(>|t|)"] < sig_level,])
sig_pathways_Con <- gsub("Pathway","",sig_pathways_Con)
print(paste("The following pathways have an AUC for Confluency significantly different (p < ",sig_level,") from the negative controls' AUC?",sep=""))
print(sig_pathways_Con[2:length(sig_pathways_Con)])
```