---
title: "Quality Control"
author: "Maia Smith"
date: "March 24, 2015"
output:
  html_document:
    keep_md: yes
---

```{r, echo=FALSE, warnings=FALSE, include = FALSE}
# install.packages("ggplot2")
# install.packages("grid")
# install.packages("plyr")
# install.packages("knitr")
# install.packages("devtools")
# install.packages("car")
# install.packages("plotly")
# install.packages("reshape2")
# install.packages("gplots")
# install.packages("RColorBrewer")
library(ggplot2)
library(grid)
library(gridExtra)
library(plyr)
library(knitr)
library(devtools)
library(car)
library(plotly)
library(reshape2)
library(gplots)
library(RColorBrewer)
py <- plotly("mas29", "8s6jru0os3")
dir = "/Users/maiasmith/Documents/SFU/ClarkeLab/ClarkeLab_github/"
#dir = "C:/Users/Dave/Documents/SFU job/Lab - muscle signaling/Dixon - myocyte expts/Maia Smith files/ClarkeLab_github/"
#dir = "/Users/mas29/Documents/ClarkeLab_github/"

# Get data
source("/Users/maiasmith/Documents/SFU/ClarkeLab/ClarkeLab_github/Scripts/GetData.R")
```

```{r setup, include=FALSE}
opts_chunk$set(out.width='1000px', dpi=200)
```

Quality Control
=============

Compare controls and treatments
-----------------------------------------------
```{r, eval=FALSE, echo=FALSE}
plot <- ggplot(sytoxG_data, aes(x=as.numeric(time_elapsed), y=as.numeric(phenotype_value), text=Compound, group=Compound)) +
  geom_line() +
  xlab("Time Elapsed") +
  ylab("Sytox Green") +
  ggtitle("Sytox Green Over Time - Control vs Treatment") +
  facet_grid(~empty, scales = "fixed") +
  theme(panel.grid = element_blank(),
        axis.ticks.length = unit(0, "cm"),
        panel.background = element_rect(fill = "white"), 
        axis.text = element_blank())
response <- py$ggplotly(plot, kwargs=list(world_readable=FALSE, filename="SG_control_vs_treatment", fileopt="overwrite"))
url <- response$response$url
```

```{r, echo=FALSE}
url<-"https://plot.ly/~mas29/225/sytox-green-over-time-control-vs-treatment.embed?width=550&height=550" 
plotly_iframe <- paste("<center><iframe scrolling='no' seamless='seamless' style='border:none' src='", url, 
    "/800/1200' width='800' height='800'></iframe><center>", sep = "")
```
`r I(plotly_iframe)`

Compare plates for controls and treatments
-----------------------------------------------

```{r, echo=FALSE}
# compare sytoxG sparklines, faceted by plates, empty
ggplot(sytoxG_data, 
       aes(x=as.numeric(time_elapsed), y=as.numeric(phenotype_value), group=Compound)) +
  geom_line() +
  xlab("Time Elapsed") +
  ylab("Sytox Green") +
  ggtitle("Sytox Green Over Time - By Plate") +
  facet_grid(empty ~ Plate, scales = "fixed") +
  theme(panel.grid = element_blank(),
        axis.ticks.length = unit(0, "cm"),
        panel.background = element_rect(fill = "white"))

```

