---
title: "Pathways and Targets"
author: "Maia Smith"
date: "March 24, 2015"
output: html_document
---


```{r, echo=FALSE, warnings=FALSE, include = FALSE}
# install.packages("ggplot2")
# install.packages("grid")
# install.packages("plyr")
# install.packages("knitr")
# install.packages("devtools")
# install.packages("car")
# install.packages("plotly")
# install.packages("reshape2")
# install.packages("gplots")
# install.packages("RColorBrewer")
library(ggplot2)
library(grid)
library(gridExtra)
library(plyr)
library(knitr)
library(devtools)
library(car)
library(plotly)
library(reshape2)
library(gplots)
library(RColorBrewer)
py <- plotly("mas29", "8s6jru0os3")
dir = "/Users/maiasmith/Documents/SFU/ClarkeLab/ClarkeLab_github/"
#dir = "C:/Users/Dave/Documents/SFU job/Lab - muscle signaling/Dixon - myocyte expts/Maia Smith files/ClarkeLab_github/"
#dir = "/Users/mas29/Documents/ClarkeLab_github/"

# Get data
source("/Users/maiasmith/Documents/SFU/ClarkeLab/ClarkeLab_github/Scripts/GetData.R")

data_for_stats <- confluency_sytoxG_data
```

Pathway analysis 
================

Sparklines by Pathway
------------------------

```{r, eval=FALSE, echo=FALSE} 
plot <- ggplot(sytoxG_data, 
               aes(x=as.numeric(time_elapsed), y=as.numeric(phenotype_value), group=Compound,
                   text=Compound)) +
  geom_line() +
  xlab("Time Elapsed") +
  ylab("Sytox Green") +
  ggtitle("Sytox Green - Facets: Pathway") +
  facet_wrap(~Pathway, ncol=6, scales = "fixed") +
  theme(panel.grid = element_blank(),
        axis.ticks.length = unit(0, "cm"),
        panel.background = element_rect(fill = "white"),
        strip.text.x = element_text(size=4),
        axis.text = element_blank())
response <- py$ggplotly(plot, kwargs=list(world_readable=FALSE, filename="SG_sparklines_by_pathway", fileopt="overwrite"))
url <- response$response$url
```

```{r, echo=FALSE}
url<-"https://plot.ly/~mas29/227/sytox-green-facets-pathway.embed?width=550&height=550" 
plotly_iframe <- paste("<center><iframe scrolling='no' seamless='seamless' style='border:none' src='", url, "/800/1200' width='800' height='800'></iframe><center>", sep = "")
```
`r I(plotly_iframe)`

Delta (max-min) values by Pathway
----------------------------------

```{r, eval=FALSE, echo=FALSE}
plot <- ggplot(sytoxG_data_features, aes(Pathway, delta_min_max, text=Compound)) + 
  geom_point(alpha=0.4) +
  ylab("Delta (max-min)") +
  ggtitle("Sytox Green Delta (max-min) by Pathway") +
  theme(panel.grid = element_blank(),
        panel.background = element_rect(fill = "white"),
        axis.text.x = element_text(size=6, angle=75))
response <- py$ggplotly(plot, kwargs=list(world_readable=FALSE, filename="SG_delta_by_pathway", fileopt="overwrite", layout=list(hovermode="closest")))
url <- response$response$url
```

```{r, echo=FALSE}
url<-"https://plot.ly/~mas29/233.embed?width=550&height=550" 
plotly_iframe <- paste("<center><iframe scrolling='no' seamless='seamless' style='border:none' src='", url, "/800/1200' width='800' height='800'></iframe><center>", sep = "")
```
`r I(plotly_iframe)`

Target analysis
=======

Which targets are significantly different from the negative controls (measured by AUC)?
------------------------

```{r, echo=FALSE, include = FALSE}
# --> SG
fit_SG <- lm(AUC_trapezoidal_integration ~ Targets..as.supplied., data_for_stats, subset = phenotypic_Marker == "SG")
summary <-  as.data.frame(summary(fit_SG)$coef)
sig_level <- 1e-20
sig_targets_SG <- rownames(summary[summary[,"Pr(>|t|)"] < sig_level,])
sig_targets_SG <- gsub("Targets..as.supplied.","",sig_targets_SG)
print(paste("The following targets have an AUC for Sytox Green significantly different (p < ",sig_level,") from the negative controls' AUC?",sep=""))
print(sig_targets_SG[2:length(sig_targets_SG)])
```

```{r,echo=FALSE}
sytoxG_data_significant_targets_only <- sytoxG_data[which(sytoxG_data$Targets..as.supplied. %in% sig_targets_SG) , ]
ggplot(sytoxG_data_significant_targets_only) +
  geom_line(aes(x=as.numeric(time_elapsed), y=as.numeric(phenotype_value), group=Compound)) +
  geom_ribbon(data = confidence_intervals_SG, mapping = aes(x = time_elapsed, ymin = phenotype_value.NC.lower, ymax = phenotype_value.NC.upper,
                             fill = "red", colour = NULL), alpha = 0.6) +
  scale_fill_manual(name = "Legend",
                    values = c('red'),
                    labels = c('Negative Control\n99.9% C.I.')) +
  xlab("Time Elapsed") +
  ylab("Sytox Green") +
  ggtitle(paste("Sytox Green - Significant Targets (p < ", sig_level, ")",sep="")) +
  facet_wrap(~Targets..as.supplied., ncol=6, scales = "fixed") +
  theme(panel.grid = element_blank(),
        axis.ticks.length = unit(0, "cm"),
        panel.background = element_rect(fill = "white"),
        strip.text.x = element_text(size=4),
        axis.text = element_blank(),
        legend.key.size = unit(0.4, "cm"),
        legend.direction="vertical")
```
