---
title: "Target Analysis"
author: "Maia Smith"
date: "March 24, 2015"
output: html_document
---

Target Analysis
===========

Which targets are significantly different from the negative controls (measured by AUC)?
------------------------

```{r, echo=FALSE}
data_for_stats <- confluency_sytoxG_data
```

For Sytox Green:

```{r, echo=FALSE}
# --> SG
fit_SG <- lm(AUC_trapezoidal_integration ~ Targets..as.supplied., data_for_stats, subset = phenotypic_Marker == "SG")
summary <-  as.data.frame(summary(fit_SG)$coef)
sig_level <- 1e-20
sig_targets_SG <- rownames(summary[summary[,"Pr(>|t|)"] < sig_level,])
sig_targets_SG <- gsub("Targets..as.supplied.","",sig_targets_SG)
print(paste("The following targets have an AUC for Sytox Green significantly different (p < ",sig_level,") from the negative controls' AUC?",sep=""))
print(sig_targets_SG[2:length(sig_targets_SG)])
```

Sytox Green sparklines for the significant targets:

```{r,echo=FALSE, fig.width = 16, fig.height = 16}
sytoxG_data_significant_targets_only <- sytoxG_data[which(sytoxG_data$Targets..as.supplied. %in% sig_targets_SG) , ]
ggplot(sytoxG_data_significant_targets_only) +
  geom_line(aes(x=as.numeric(time_elapsed), y=as.numeric(phenotype_value), group=Compound)) +
  geom_ribbon(data = confidence_intervals_SG, mapping = aes(x = time_elapsed, ymin = phenotype_value.NC.lower, ymax = phenotype_value.NC.upper,
                             fill = "red", colour = NULL), alpha = 0.6) +
  scale_fill_manual(name = "Legend",
                    values = c('red'),
                    labels = c('Negative Control\n99.9% C.I.')) +
  xlab("Time Elapsed") +
  ylab("Sytox Green") +
  ggtitle(paste("Sytox Green - Significant Targets (p < ", sig_level, ")",sep="")) +
  facet_wrap(~Targets..as.supplied., ncol=6, scales = "fixed") +
  theme(panel.grid = element_blank(),
        axis.ticks.length = unit(0, "cm"),
        panel.background = element_rect(fill = "white"),
        axis.text = element_blank(),
        legend.key.size = unit(0.4, "cm"),
        legend.direction="vertical")
```

For Confluency:

```{r, echo=FALSE}
# --> Con
fit_Con <- lm(AUC_trapezoidal_integration ~ Targets..as.supplied., data_for_stats, subset = phenotypic_Marker == "Con")
summary <-  as.data.frame(summary(fit_Con)$coef)
sig_level <- 1e-20
sig_targets_Con <- rownames(summary[summary[,"Pr(>|t|)"] < sig_level,])
sig_targets_Con <- gsub("Targets..as.supplied.","",sig_targets_Con)
print(paste("The following targets have an AUC for Confluency significantly different (p < ",sig_level,") from the negative controls' AUC?",sep=""))
print(sig_targets_Con[2:length(sig_targets_Con)])
```

Confluency sparklines for the significant targets:

```{r,echo=FALSE, fig.width = 16, fig.height = 16}
confluency_data_significant_targets_only <- confluency_data[which(confluency_data$Targets..as.supplied. %in% sig_targets_Con) , ]
ggplot(confluency_data_significant_targets_only) +
  geom_line(aes(x=as.numeric(time_elapsed), y=as.numeric(phenotype_value), group=Compound)) +
  geom_ribbon(data = confidence_intervals_Con, mapping = aes(x = time_elapsed, ymin = phenotype_value.NC.lower, ymax = phenotype_value.NC.upper,
                                                             fill = "red", colour = NULL), alpha = 0.6) +
  scale_fill_manual(name = "Legend",
                    values = c('red'),
                    labels = c('Negative Control\n99.9% C.I.')) +
  xlab("Time Elapsed") +
  ylab("Confluency") +
  ggtitle(paste("Confluency - Significant Targets (p < ", sig_level, ")",sep="")) +
  facet_wrap(~Targets..as.supplied., ncol=6, scales = "fixed") +
  theme(panel.grid = element_blank(),
        axis.ticks.length = unit(0, "cm"),
        panel.background = element_rect(fill = "white"),
        axis.text = element_blank(), 
        legend.key.size = unit(0.4, "cm"),
        legend.direction="vertical")
```
